services:
  - type: web
    name: portfolio-backend
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: ADMIN_EMAIL
        value: yoogesh06@gmail.com
      - key: EMAIL_APP_PASSWORD
        value: iedk xtbp tffh ccgs
